# Generated by Django 4.0.1 on 2022-01-28 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ImageField(default='head.png', upload_to='profile_pics')),
                ('body', models.ImageField(default='body.png', upload_to='profile_pics')),
                ('arm_l', models.ImageField(default='arm_l.png', upload_to='profile_pics')),
                ('arm_r', models.ImageField(default='arm_r.png', upload_to='profile_pics')),
                ('leg_l', models.ImageField(default='leg_l.png', upload_to='profile_pics')),
                ('leg_r', models.ImageField(default='leg_r.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
