# Generated by Django 4.0.1 on 2022-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_arm_l_remove_profile_arm_r_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='arm_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='arm_r',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='body',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='leg_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='leg_r',
            field=models.BooleanField(default=False),
        ),
    ]
