# Generated by Django 4.0.1 on 2022-01-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_points',
            field=models.IntegerField(default=100),
        ),
    ]
