# Generated by Django 4.0.1 on 2022-01-29 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_finish', models.BooleanField(default=False)),
                ('user2_finish', models.BooleanField(default=False)),
                ('user1_points', models.IntegerField(default=0)),
                ('user2_points', models.IntegerField(default=0)),
                ('user1_bonus_points', models.IntegerField(default=0)),
                ('user2_bonus_points', models.IntegerField(default=0)),
                ('game_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('matrix_id', models.CharField(max_length=10)),
                ('user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utente1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utente2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_game',
            },
        ),
    ]
